title: Performance Accountability Council

theme: uswds-jekyll

styles:
  - /assets/uswds/css/uswds.min.css
  - /assets/css/styles.css

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true
